#ifndef COMPILER_H
#define COMPILER_H

#include "tree.hpp"
#include "bytecode.hpp"
#include "token.hpp"
#include "vm.hpp"
#include <vector>

class Compiler{
private:
    void genAssignmentBc(std::vector<bytecode> &, Tree);
public:
    /// @brief Converts the AST tree to bytecode for the vm to execute
    /// @param  Tree which was generated by the parser
    /// @param  bc vector to store the generated bytecode this vector will be passed to the vm
    void compile(std::vector<bytecode>, Tree);
};

#endif